name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello
        run: echo 'Hello World'

      - name: Build
        run: echo 'Build World'

      - name: Destroy
        run: echo 'Destroy World'
